name: CI/CD Pipeline

on:
  push:
    branches: [ main, feature/email-notification ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Install dependencies
        run: |
          cd functions/Email_Notifications
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with SAM
        run: sam build

      - name: Deploy with SAM
        if: github.ref == 'refs/heads/main'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-file samconfig.toml
