on:

name: Deploy

on:
  workflow_run:
    workflows: ["Build and Validate"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: >-
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Install dependencies
        run: |
          cd functions/Email_Notifications
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy with SAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --capabilities CAPABILITY_NAMED_IAM --config-file samconfig.toml
